
fs-assistant:

  volumes:
    localVideo:
      type: local
      path: /somePath
    folderCleanup:
      type: local
      path: C:\Users\me\Documents\test\cleanup

  pipes:
    local-cleanup-pipe:
      task:
        # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
        cron: 0/30 * * * * *
        force-suspend: false
        simulation-mode: false
        max-messages-per-poll: 30
      # target-volume is not necessary to cleaner task
      source-volume-meta:
        volume-ref: folderCleanup
        max-expected-files: 500
        # subfolders are always processed recursively, nex param states if folder itself will be handled
        filter-out-folders: false
        file-extensions:
        - "*.h264"
        - "*.avi"
