
fs-assistant:

  volumes:
    raspberryVideo:
      type: sftp
      path: /media/pi/video
      host:
      port: 22
      user:
      private-key:
      private-key-passphrase:
      # password is optional if no private-key & passphrase were used
      password:
    localVideo:
      type: local
      path: /home/dlink/ftp/files/raspberry
    folderCleanup:
      type: local
      path: /home/dlink/ftp/files/

  file-uploader:
    task:
      # we don't really need it so for, TODO: test it out
      force-suspend: true
    source-volume:
      volume-ref: localVideo
      auto-create-directory: true
    target-volume:
      volume-ref: some-other-volume-here
      file-extensions:
      - *.*
      delete-source-files: true
    # channel is not of interest to end user
    channel: uploadFilesChannel

  file-downloader:
    task:
      # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
      cron: 0 0/15 * * * * *
      force-suspend: false
      simulation-mode: false
      debug-logger-level: false
    source-volume:
      # must be a remote folder (*file downloader*)
      volume-ref: raspberryVideo
      file-extensions:
        - *.h264
      delete-source-files: true
    target-volume:
      # must be a local folder (*file downloader*)
      volume-ref: localVideo
      auto-create-directory: true
    # channel is not of interest to end user
    channel: downloadFilesChannel

  folder-cleaner:
    task:
      # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
      cron: 0 7 * * * * *
      force-suspend: false
      simulation-mode: false
      debug-logger-level: false
    # source-volume doesn't make sense to cleaner task
    target-volume:
      volume-ref: folderCleanup
      file-extensions:
        - *.h264
        - *.avi
    # channel is not of interest to end user
    channel: folderCleanupChannel
