
fs-assistant:
  local-source:
    folder: /media/pi/video
    max-expected-files-before-removal: 2000
    file-extensions:
      - *.h264

  file-transfer:
    # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
    cron: 0 0/15 * * * * *
    remote-destination-folder: /files/raspberry
    inputChannelId: transferInputChannel
    suspend: false

  folder-cleaner:
    # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
    cron: 0 7 * * * * *
    inputChannelId: cleanerInputChannel
    suspend: false
  