
fs-assistant:
  local-source:
    folder: /media/pi/video
    max-expected-files: 2000
    file-extensions:
      - *.h264

  sftp-source:
    host: 
    private-key: 
    private-key-passphrase: 
    port: 22
    user: 

  file-transfer:
    # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
    cron: 0 0/15 * * * * *
    remote-destination-folder: /files/raspberry
    inputChannelId: filesTransferChannel
    suspend: false

  folder-cleaner:
    # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
    cron: 0 7 * * * * *
    inputChannelId: folderCleanerChannel
    suspend: false
  
