
fs-assistant:
  volumes:
    folderCleanup:
      type: local
      path: /home/dlink/ftp/files

  pipes:
    local-cleanup-pipe:
      task:
        # Order: <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
        cron: 0 0 8/1 * * *
        force-suspend: false
        simulation-mode: false
        max-messages-per-poll: 1000
      # target-volume is not necessary to cleaner task
      source-volume-meta:
        volume-ref: folderCleanup
        # next does not filter, but just keeps a max size of files to recall before potentially grab the same files again
        max-expected-files: 1000
        filter:
          # 172800 seconds = 2 days
          file-modification-min-age-seconds: 259200
          # subfolders are always processed recursively, nex param states if folder itself will be handled
          filter-out-folders: false
          file-extensions:
          - "*.h264"
          - "*.avi"
